afup_barometre_homepage:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /report/company_type
        permanent: true

afup_barometre_report:
    pattern:  /report/{reportName}
    defaults: { _controller: AfupBarometreBundle:Default:index }
