afup_barometre_homepage:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /about
        permanent: true


afup_barometre_about:
    pattern: /about
    defaults: {_controller: AfupBarometreBundle:About:index }

afup_barometre_report:
    pattern:  /report/{reportName}
    defaults: { _controller: AfupBarometreBundle:Default:index }
