afup_barometre_homepage:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /about
        permanent: true

afup_barometre_about:
    path: /about
    defaults: {_controller: AfupBarometreBundle:About:index }

afup_barometre_report:
    path:  /report/{reportName}
    defaults: { _controller: AfupBarometreBundle:Default:index }
